# セルのスタイル
# sample:
#   font:
#     name: メイリオ # フォント名
#     size: 20  # 文字サイズ
#     underline: single # アンダーライン
#     bold: True  # 太字
#     color: FF0F0F # 色
#   alignment:
#     horizontal: center # 文字位置（水平）
#     vertical: top # 文字位置（垂直）
#   fill:
#     patternType: solid # 塗りつぶしのスタイル
#     fgColor: c0c0c0 # 色
#   border:
#     top: 
#       border_style: medium # 枠線の種類
#       color: 2f4f4f
#     bottom: 
#       border_style: medium
#       color: ffa500
#     diagonal: 
#       border_style: hair
#       color: dc143c

# 基本
basic:
  font:
    name: メイリオ
    size: 11

# 見出し
h1:
  font:
    name: メイリオ
    size: 19
    bold: True
h2:
  font:
    name: メイリオ
    size: 17
    bold: True
h3:
  font:
    name: メイリオ
    size: 15
    bold: True
h4:
  font:
    name: メイリオ
    size: 13
    bold: True
h5:
  font:
    name: メイリオ
    bold: True

highlight:
  font:
    name: メイリオ
    bold: True
    color: ff0000

hyperlink:
  font:
    name: メイリオ
    color: 0075c2
    underline: single

table_head:
  font:
    name: メイリオ
    bold: True
  fill:
    patternType: solid
    fgColor: 9fc24d
  alignment:
    horizontal: center
  border:
    top:
      border_style: thin
      color: 004d25
    bottom:
      border_style: thin
      color: 004d25
    left:
      border_style: thin
      color: 004d25
    right:
      border_style: thin
      color: 004d25

table_value:
  font:
    name: メイリオ
  alignment:
    horizontal: center
  border:
    top:
      border_style: thin
      color: 004d25
    bottom:
      border_style: thin
      color: 004d25
    left:
      border_style: thin
      color: 004d25
    right:
      border_style: thin
      color: 004d25

df_head:
  font:
    name: メイリオ
    bold: True
    color: ffffff
  fill:
    patternType: solid
    fgColor: 192f60
  alignment:
    horizontal: center
  border:
    top:
      border_style: thin
      color: 192f60
    bottom:
      border_style: thin
      color: 192f60
    left:
      border_style: thin
      color: 192f60
    right:
      border_style: thin
      color: 192f60

df_value:
  font:
    name: メイリオ
  alignment:
    horizontal: center
  border:
    top:
      border_style: thin
      color: 192f60
    bottom:
      border_style: thin
      color: 192f60
    left:
      border_style: thin
      color: 192f60
    right:
      border_style: thin
      color: 192f60